### ISSUE TITLE
Cocoapods validation failing - not compatible with macOS

### ISSUE THREAD

**Issue by simonmcl** [trustwallet/wallet-core#1284]
**Describe the bug**

I'm trying to build a swift library for Tezos that incorporates your library. I've had to disable MacOS support for it because cocoapods trunk validation is failing with the message:

```
- ERROR | [OSX] unknown: Encountered an unknown error (The platform of the target `App` (macOS 10.12) is not compatible with `TrustWalletCore (2.5.6)`, which does not support `macOS`.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:441:in `validate_platform'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:123:in `block (3 levels) in resolver_specs_by_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:119:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:119:in `block (2 levels) in resolver_specs_by_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:107:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:107:in `block in resolver_specs_by_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:106:in `tap'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:106:in `resolver_specs_by_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:95:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:577:in `block in download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:577:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:577:in `download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:399:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:393:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:393:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/validator.rb:130:in `validate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:96:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:75:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:75:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

[!] camlKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

Your podspec includes `s.osx.deployment_target = '10.12'`, which mine copies. There seems to be some issue or compilation error when building for MacOS

**To Reproduce**

Clone my library: https://gitlab.com/camlcase-dev/camlkit

Add `s.osx.deployment_target = '10.12'` to the podspec and run `pod lib lint camlKit.podspec --verbose`

**Expected behavior**

For validation to pass with osx included

**Comment by hewigovens** [comment]
See https://github.com/trustwallet/wallet-core/pull/1178, we will migrate to xcframework to fix this later

**Comment by SirJosh1987** [comment]
New to this like from knowing nothing
