### ISSUE TITLE
Bitcoin private key support

### ISSUE THREAD

**Issue by rasouliali1379** [trustwallet/wallet-core#1526]
Would you add bitcoin private encoding/decoding support in future?

**Comment by hewigovens** [comment]
you meant WIF? we removed this functionality, just use `Base58` to decode

**Comment by rasouliali1379** [comment]
I used Based58 like this 

`        val privateKey = PrivateKey(Base58.decode("L3hQFsFccMtsS2hjHFUmazGzwx2q5L2RXP6TWqZGLVeQULwnopTw"))
`

but it throw this exeption

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.txsigningtest, PID: 29030
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.txsigningtest/com.example.txsigningtest.MainActivity}: java.security.InvalidParameterException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.security.InvalidParameterException
        at wallet.core.jni.PrivateKey.<init>(PrivateKey.java:55)
        at com.example.txsigningtest.LitecoinTransactionMaker.createTransaction(BitcoinTransactionMaker.kt:24)
        at com.example.txsigningtest.MainActivity.onCreate(MainActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
`

**Comment by hewigovens** [comment]
try `Base58.decodeNoCheck`

**Comment by rasouliali1379** [comment]
The error wasn't for decoding

I passed the private key to decoder function like this :

`val decoded = Base58.decode("KwLtE....27iYX5...HZAfcSt4....RAJtQX")
        val privateKey = PrivateKey(decoded)`

and I got this error for the second line :

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.txsigningtest, PID: 27019
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.txsigningtest/com.example.txsigningtest.MainActivity}: java.security.InvalidParameterException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.security.InvalidParameterException
        at wallet.core.jni.PrivateKey.<init>(PrivateKey.java:55)
        at com.example.txsigningtest.LitecoinTransactionMaker.createTransaction(LitecoinTransactionMaker.kt:25)
        at com.example.txsigningtest.MainActivity.onCreate(MainActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:8093)
        at android.app.Activity.performCreate(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)`

**Comment by hewigovens** [comment]
take a look at https://en.bitcoin.it/wiki/Wallet_import_format, you need to drop first byte
