### ISSUE TITLE
EIP-712 signing fails on eth_signTypedData setup

### ISSUE THREAD

**Issue by onkaraman** [trustwallet/wallet-core#3046]
### Discussed in https://github.com/trustwallet/wallet-core/discussions/3045

<div type='discussions-op-text'>

<sup>Originally posted by **onkaraman** March 31, 2023</sup>
Hi all,

the following code works with MetaMask, but on Trust Wallet I have issues:

```
let signature = await window.ethereum.request({
	method: 'eth_signTypedData_v4',
	params: [connectedAddress,
		JSON.stringify(EIP712types.newRecord(this.state.createName, this.state.createSNr))
	]
});
```

The value of `JSON.stringify(EIP712types.newRecord(this.state.createName, this.state.createSNr))` is
```
{
	"types": {
		"EIP712Domain": [{
			"name": "name",
			"type": "string"
		}, {
			"name": "version",
			"type": "string"
		}, {
			"name": "chainId",
			"type": "uint256"
		}, {
			"name": "verifyingContract",
			"type": "address"
		}],
		"NewRecord": [{
			"name": "productName",
			"type": "string"
		}, {
			"name": "productUID",
			"type": "string"
		}]
	},
	"primaryType": "NewRecord",
	"domain": {
		"name": "MyDomain",
		"version": "1",
		"chainId": 1337,
		"verifyingContract": "..."
	},
	"message": {
		"productName": "MGS1PS1",
		"productUID": "MGS1PS1"
	}
}
```

Trust Wallet returns the error:

```
SyntaxError: Unexpected non-whitespace character after JSON at position 1
    at JSON.parse (<anonymous>)
    at g.value (inpage.js:2:42406)
    at inpage.js:2:40108
```

I'm testing my dApp locally with ganache.

</div>

**Comment by zlace0x** [comment]
I'm facing a similar issue on `eth_signTypedData` only on trust iOS app (works on android) via walletconnect. Signing a erc20 permit works fine.

```javascript
// Domain 
{
    types: {
      MetaTransaction: [
        { name: "nonce", type: "uint256" },
        { name: "from", type: "address" },
        { name: "functionSignature", type: "bytes" },
      ],
    },
    primaryType: "MetaTransaction",
    domain: {
      name: domainName,
      version: "1",
      chainId,
      verifyingContract,
    },
    message: {
      nonce,
      from,
      functionSignature,
    },
  }
}
// response
{
    "code": -32000,
    "message": "The operation couldn’t be completed. (TrustWalletConnect.WCError error 1.)"
}
```
