### ISSUE TITLE
[BUILD ISSUE]: tools/ios-release

### ISSUE THREAD

**Issue by Amurmurmur** [trustwallet/wallet-core#3495]
**Describe the bug**
Trying to release a a wallet-core into a private cocoapods repo
I changed a `tools/ios-release.sh` slightly to
```
pod repo push --verbose --allow-warnings REPO_NAME ${podspec}
```
instead of pod trunk push

**OS: MacOS 14.0 (23A344)
XCode Version 15.0 (15A240d)**

**To Reproduce**
1. tools/bootstrap.sh
2. tools/ios-release

**Expected behavior**

**Screenshots**

**Additional context**
Log after runninng tools/ios-release.sh

```
 /var/folders/wq/56nzs2qn5y9fclq9jnzw6mvc0000gn/T/CocoaPods-Lint-20231020-30714-sov4bh-TrustWalletCore/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'SwiftProtobuf' from project 'Pods')
    ** BUILD SUCCEEDED **
    
   Testing with `xcodebuild`. 
 -> TrustWalletCore (3.3.3)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Target dependency graph (4 targets)
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'SwiftProtobuf' from project 'Pods')
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'Pods-App' from project 'Pods')
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'App' from project 'App')
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'SwiftProtobuf' from project 'Pods')
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | [TrustWalletCore/Types,TrustWalletCore/Core] xcodebuild:  Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'SwiftProtobuf' from project 'Pods')
    - ERROR | [TrustWalletCore/Types] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [TrustWalletCore/Core] file patterns: The `vendored_frameworks` pattern did not match any file.

[!] The `TrustWalletCore.podspec` specification does not validate.

/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/repo/push.rb:156:in `block in validate_podspec_files'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/repo/push.rb:140:in `each'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/repo/push.rb:140:in `validate_podspec_files'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/repo/push.rb:81:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `<main>'
```

**Comment by weixuefeng** [comment]
have you execute `./tools/generate-files` ?

**Comment by weixuefeng** [comment]
```
    - ERROR | [TrustWalletCore/Types,TrustWalletCore/Core] file patterns: The `source_files` pattern did not match any file.
```
what's the `source_files` define?

i got `walletCore.xcframework` & `swiftProtobuf.xcframework` by
```
./tools/bootstrap.sh
./tools/generate-files
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
make -Cbuild
./tools/ios-build && ./tools-xcframework
```
