### ISSUE TITLE
 No implementation found for long wallet.core.jni.HDWallet.nativeCreateWithMnemonic(java.lang.String, java.lang.String)

### ISSUE THREAD

**Issue by wangpeng1582655** [TrustWallet/wallet-core#511]
On  Android:

implementation 'com.trustwallet.walletcore:walletcore:0.12.1'

HDWallet hdWallet = new HDWallet(mnemonic,pass)，throws UnsatisfiedLinkError

java.lang.UnsatisfiedLinkError: No implementation found for long wallet.core.jni.HDWallet.nativeCreateWithMnemonic(java.lang.String, java.lang.String) (tried Java_wallet_core_jni_HDWallet_nativeCreateWithMnemonic and Java_wallet_core_jni_HDWallet_nativeCreateWithMnemonic__Ljava_lang_String_2Ljava_lang_String_2)
                                                                        at wallet.core.jni.HDWallet.nativeCreateWithMnemonic(Native Method)
                                                                        at wallet.core.jni.HDWallet.<init>(HDWallet.java:54)
                                                                        at wallet.core.jni.SecondActivity.onCreate(SecondActivity.java:26)
                                                                        at android.app.Activity.performCreate(Activity.java:7383)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
                                                                        at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                        at android.os.Looper.loop(Looper.java:166)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by eddywm** [comment]
Hey @wangpeng1582655 did you try to load the library before call.
This is likely the reason of the crash.
You can look in tests the way we do it.

**Comment by wangpeng1582655** [comment]
> Hey @wangpeng1582655 did you try to load the library before call.
> This is likely the reason of the crash.
> You can look in tests the way we do it.

thanks，load the library， it works good!
