### ISSUE TITLE
Build Issue - generate-files - undefined method `filter'

### ISSUE THREAD

**Issue by nezero** [TrustWallet/wallet-core#527]
## Expected Behavior

`./tools/generate-files `

Should run

## Current Behavior

`(erb):88:in 'block in <main>': undefined method 'filter' for #<Array:0x00007fe7ad8267b0> (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in 'eval'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in 'result'
	from codegen/bin/coins:38:in 'block in <main>'
	from codegen/bin/coins:35:in 'each'
	from codegen/bin/coins:35:in  '<main>'
`

## Steps to Reproduce (for bugs)

```
1. Checkout master branch OSX.
2. run gerate-files
3. observe error
```

## Context

I was about to submit a pull request and merged in the latest commits from master then started getting this issue. 

Now I cannot generate the files, build the code and run the tests.

## Your Environment

OSX
Followed these instructions https://developer.trustwallet.com/wallet-core/contributing#before-you-start

**Comment by nezero** [comment]
`export PATH="/usr/local/opt/ruby/bin:$PATH"`

Running this first fixes the issue, default version of ruby was being used.
